base_model: NousResearch/Meta-Llama-3-8B-Instruct
base_model_config:
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
model_params_count: 0
job_id:
hpo_run: false
dataloader_num_workers: 8
load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: llama3
datasets:
dataset_prepared_path:
val_set_size: 0.1
output_dir: miner_id_24

sequence_len: 2048
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: true
trust_remote_code: true
gpu_memory_limit: 80GiB

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true

gradient_accumulation_steps: 4
micro_batch_size: 8
eval_batch_size: 8
optimizer: adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-4
group_by_length: true

train_on_inputs: false
bf16: true
tf32: true
fp16: false

gradient_checkpointing: true
resume_from_checkpoint:
local_rank:
flash_attention: true
s2_attention:

wandb_project: Gradients-On-Demand
wandb_mode: online
wandb_run: your_name
wandb_runid: default

hub_model_id:
hub_repo:
hub_strategy: checkpoint
hub_token:

num_epochs: 4
logging_steps: 5
save_total_limit: 5
early_stopping: true
early_stopping_patience: 3
save_strategy: steps
metric_for_best_model: eval_loss
save_total_limit: 5
greater_is_better: false
eval_strategy: steps
save_steps: 40
eval_steps: 20
warmup_steps: 120
eval_table_size:
eval_max_new_tokens: 128
max_steps: 10000

debug:

weight_decay: 0.01
plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_layer_norm: true
liger_fused_linear_cross_entropy: true