async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 120
max_train_epochs  = 120
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
learning_rate = 0.00001
loss_type = "l1"
lr_scheduler        = "cosine"
lr_scheduler_args   = []
max_bucket_reso = 2048
max_data_loader_n_workers = 4
max_grad_norm = 0.5
max_token_length = 75
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "bf16"
network_alpha = 32
network_args = []
network_dropout = 0.05
network_dim = 64
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_type = "AdamW8Bit"
optimizer_args      = ["weight_decay=0.01"]
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 5
save_model_as = "safetensors"
save_precision = "bf16"
scale_weight_norms = 5
text_encoder_lr = 1e-5
train_batch_size = 8
train_data_dir = ""
training_comment = ""
unet_lr = 3e-4
xformers = true
